### TEST GET / WEBSITE
GET http://localhost:8383

### TEST GET /dashboard WEBSITE
GET http://localhost:8383/dashboard

### DATA ENDPOINT
GET http://localhost:8383/api/data

### DATA CREATE (post) 
POST http://localhost:8383/api/data
Content-Type: application/json

{
  "name": "Mark",
  "age": 37
}

### DELETE END POINT
DELETE http://localhost:8383/api/data